// <auto-generated />
using System;
using Caldo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Caldo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200606210055_test1")]
    partial class test1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Caldo.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Pizze"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Sendvici"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Palacinke"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Rostilj"
                        });
                });

            modelBuilder.Entity("Caldo.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("OrderPlaced")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OrderTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("OrderId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Caldo.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("PizzaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PizzaId");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("Caldo.Models.Pizza", b =>
                {
                    b.Property<int>("PizzaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaliOpis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NaStanju")
                        .HasColumnType("bit");

                    b.Property<bool>("Najprodavanija")
                        .HasColumnType("bit");

                    b.Property<string>("SlikaThumbUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlikaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VelikiOpis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PizzaId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Pizza");

                    b.HasData(
                        new
                        {
                            PizzaId = 1,
                            CategoryId = 1,
                            Cena = 170m,
                            Ime = "Margarita",
                            MaliOpis = "kecap, kackavalj, origano",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\MenuThumb\\pica1mala.jpg",
                            SlikaUrl = "\\Images\\Menu\\pica1.jpg",
                            VelikiOpis = "Regardless what else comes atop your pizza, a few fresh basil leaves will taste amazing with it. This simple summertime pizza would make a delicious cookout appetizer or light dinner paired with a salad."
                        },
                        new
                        {
                            PizzaId = 2,
                            CategoryId = 1,
                            Cena = 220m,
                            Ime = "Napolitana",
                            MaliOpis = "kecap, kackavalj, tunjevina, origano",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\MenuThumb\\pica2mala.jpg",
                            SlikaUrl = "\\Images\\Menu\\pica2.jpg",
                            VelikiOpis = "Who doesn’t love a little extra cheese for the perfect cheese-pull picture? We sure do. You might want to check with your local pizza joint to see how much cheese actually comes with an “extra cheese” order, because apparently, it’s hotly debated."
                        },
                        new
                        {
                            PizzaId = 3,
                            CategoryId = 1,
                            Cena = 200m,
                            Ime = "Capriciosa",
                            MaliOpis = "kecap, kackavalj, sunka, pecurke, origano",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\MenuThumb\\pica3mala.jpg",
                            SlikaUrl = "\\Images\\Menu\\pica3.jpg",
                            VelikiOpis = "Ham is often paired with the aforementioned pineapple for Hawaiian pizzas, but it can be delicious with other toppings (we’re looking at you, meat-lovers’ pizza). For a fancier feel, try prosciutto, or Italian ham."
                        },
                        new
                        {
                            PizzaId = 4,
                            CategoryId = 1,
                            Cena = 200m,
                            Ime = "Vegetariana",
                            MaliOpis = "kecap, kackavalj, pavlaka, pecurke, origano",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\MenuThumb\\pica4mala.jpg",
                            SlikaUrl = "\\Images\\Menu\\pica4.jpg",
                            VelikiOpis = "Some prefer mild, others spicy, and Southerners Conecuh, but sausage is consistently a favorite pizza topping of Americans. This cast-iron pizza recipe gives you another reason to love that skillet."
                        },
                        new
                        {
                            PizzaId = 5,
                            CategoryId = 1,
                            Cena = 200m,
                            Ime = "Romana",
                            MaliOpis = "kecap, kackavalj, sunka, masline, origano",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\MenuThumb\\pica5mala.jpg",
                            SlikaUrl = "\\Images\\Menu\\pica5.jpg",
                            VelikiOpis = "Green, red, yellow, or orange, peppers add a missing crunchy element to chewy, cheesy pizza. This sheet-pan recipe is the easiest way to serve pizza to a crowd, which is code for, “You should have a pizza party.”"
                        },
                        new
                        {
                            PizzaId = 6,
                            CategoryId = 1,
                            Cena = 240m,
                            Ime = "Quatro Stagione",
                            MaliOpis = "kecap, kackavalj, sunka, kobasica, pecurke, masline, jaje, origano",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\MenuThumb\\pica6mala.jpg",
                            SlikaUrl = "\\Images\\Menu\\pica6.jpg",
                            VelikiOpis = "In case you haven’t noticed the trend, meat is always popular on top of pizzas. Whether you’re going for a dressier steak pizza, a kid-friendly cheeseburger pizza, or a pizza topped with meatballs (actually a thing), beef always has a place on pizza."
                        },
                        new
                        {
                            PizzaId = 7,
                            CategoryId = 1,
                            Cena = 240m,
                            Ime = "Vesuvio",
                            MaliOpis = "kecap, kackavalj, sunka, slanina, jaje, pecurke, crni luk, origano",
                            NaStanju = false,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\MenuThumb\\pica7mala.jpg",
                            SlikaUrl = "\\Images\\Menu\\pica7.jpg",
                            VelikiOpis = "Spinach is a delicious way to add a little green to your pizza. Another popular green found on pizzas is arugula. Unlike spinach, which is usually cooked with the pizza, arugula is placed fresh on top of the pizza for a fresh, peppery pop. Try our Fig Flatbread for an arugula-topped pizza recipe."
                        },
                        new
                        {
                            PizzaId = 8,
                            CategoryId = 1,
                            Cena = 250m,
                            Ime = "Kalcona(zatvorena pizza)",
                            MaliOpis = "kecap, kackavalj, sunka, pecurke, kobasica, origano",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\MenuThumb\\pica8mala.jpg",
                            SlikaUrl = "Images/Menu/pica8.jpg",
                            VelikiOpis = "This earthy topping can be divisive in the kitchen, but many agree that it fits right in on a pizza, and this breakfast recipe is a perfect excuse to try eggs on a pizza. Spoiler: You’re going to love it."
                        },
                        new
                        {
                            PizzaId = 9,
                            CategoryId = 1,
                            Cena = 250m,
                            Ime = "Diablo",
                            MaliOpis = "kecap, kackavalj, sunka, pecurke, pavlaka, kobasica, origano",
                            NaStanju = true,
                            Najprodavanija = true,
                            SlikaThumbUrl = "\\Images\\MenuThumb\\pica9mala.jpg",
                            SlikaUrl = "Images/Menu/pica9.jpg",
                            VelikiOpis = "The winner winner of weeknight meals goes well on pizzas, too! BBQ chicken, buffalo chicken, and chicken bacon ranch are common pizza orders that contain this protein."
                        },
                        new
                        {
                            PizzaId = 10,
                            CategoryId = 1,
                            Cena = 200m,
                            Ime = "Mexicana",
                            MaliOpis = "kecap, kackavalj, sunka, pecurke, tobasko, feferone, origano",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\MenuThumb\\pica10mala.jpg",
                            SlikaUrl = "\\Images\\Menu\\pica10.jpg",
                            VelikiOpis = "Whether they crisp up in the oven or go on the pizza caramelized, onions are a popular topping that add a little salty or a little sweet, depending how they’re prepared. Red onions often accompany barbecue chicken pizzas, while white and yellow onions are popular for supreme pizzas."
                        },
                        new
                        {
                            PizzaId = 11,
                            CategoryId = 1,
                            Cena = 250m,
                            Ime = "Burini",
                            MaliOpis = "kecap, kackavalj, vrat, kajmak, pecurke, jaje, origano",
                            NaStanju = false,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\MenuThumb\\pica11mala.jpg",
                            SlikaUrl = "\\Images\\Menu\\pica11.jpg",
                            VelikiOpis = "People either love or hate olives, but even if you’re not a fan, you might actually like the salty bite black olives add to a generously topped pizza. Or you’ll just pick them all off. Either way."
                        },
                        new
                        {
                            PizzaId = 12,
                            CategoryId = 1,
                            Cena = 210m,
                            Ime = "Posna Pizza",
                            MaliOpis = "kecap, pecurke, tunjevina, masline, origano",
                            NaStanju = false,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\MenuThumb\\pica12mala.jpg",
                            SlikaUrl = "\\Images\\Menu\\pica12.jpg",
                            VelikiOpis = "People either love or hate olives, but even if you’re not a fan, you might actually like the salty bite black olives add to a generously topped pizza. Or you’ll just pick them all off. Either way."
                        },
                        new
                        {
                            PizzaId = 13,
                            CategoryId = 1,
                            Cena = 250m,
                            Ime = "Caldo Special",
                            MaliOpis = "kecap, kackavalj, prsut, sampinjoni, jaje, pavlaka, masline, origano",
                            NaStanju = false,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\MenuThumb\\pica13mala.jpg",
                            SlikaUrl = "\\Images\\Menu\\pica13.jpg",
                            VelikiOpis = "People either love or hate olives, but even if you’re not a fan, you might actually like the salty bite black olives add to a generously topped pizza. Or you’ll just pick them all off. Either way."
                        },
                        new
                        {
                            PizzaId = 14,
                            CategoryId = 1,
                            Cena = 250m,
                            Ime = "Specijal",
                            MaliOpis = "kecap, kackavalj, vrat, kobasica, jaje, pecurke, luk, origano",
                            NaStanju = false,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\MenuThumb\\pica14mala.jpg",
                            SlikaUrl = "\\Images\\Menu\\pica14.jpg",
                            VelikiOpis = "People either love or hate olives, but even if you’re not a fan, you might actually like the salty bite black olives add to a generously topped pizza. Or you’ll just pick them all off. Either way."
                        },
                        new
                        {
                            PizzaId = 15,
                            CategoryId = 1,
                            Cena = 250m,
                            Ime = "Piroska",
                            MaliOpis = "kecap, kackavalj, sunka, pecurke, pavlaka, origano",
                            NaStanju = false,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\MenuThumb\\pica15mala.jpg",
                            SlikaUrl = "\\Images\\Menu\\pica15.jpg",
                            VelikiOpis = "People either love or hate olives, but even if you’re not a fan, you might actually like the salty bite black olives add to a generously topped pizza. Or you’ll just pick them all off. Either way."
                        },
                        new
                        {
                            PizzaId = 16,
                            CategoryId = 2,
                            Cena = 50m,
                            Ime = "Sendvic prazan",
                            MaliOpis = "lepinja",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            SlikaUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 17,
                            CategoryId = 2,
                            Cena = 240m,
                            Ime = "Sendvic pecurke",
                            MaliOpis = "lepinja, kackavalj, sunka, pecurke salata",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Sendvic.jpg",
                            SlikaUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 18,
                            CategoryId = 2,
                            Cena = 240m,
                            Ime = "Sendvic ruska",
                            MaliOpis = "lepinja, kackavalj, sunka, ruska salata",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Sendvic.jpg",
                            SlikaUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 19,
                            CategoryId = 2,
                            Cena = 240m,
                            Ime = "Sendvic govedja",
                            MaliOpis = "lepinja, kackavalj, sunka, govedja salata",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Sendvic.jpg",
                            SlikaUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 20,
                            CategoryId = 2,
                            Cena = 240m,
                            Ime = "Sendvic pileca",
                            MaliOpis = "lepinja, kackavalj, sunka, pileca salata",
                            NaStanju = true,
                            Najprodavanija = true,
                            SlikaThumbUrl = "\\Images\\Carousel\\Sendvic.jpg",
                            SlikaUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 21,
                            CategoryId = 2,
                            Cena = 320m,
                            Ime = "Sendvic prsut",
                            MaliOpis = "lepinja, kackavalj, njegoski prsut, salata po izboru",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Sendvic.jpg",
                            SlikaUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 22,
                            CategoryId = 2,
                            Cena = 290m,
                            Ime = "Sendvic pecenica",
                            MaliOpis = "lepinja, kackavalj, pecenica, salata po izboru",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Sendvic.jpg",
                            SlikaUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 23,
                            CategoryId = 2,
                            Cena = 290m,
                            Ime = "Sendvic suvi vrat",
                            MaliOpis = "lepinja, kackavalj, suvi vrat, salata po izboru",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Sendvic.jpg",
                            SlikaUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 24,
                            CategoryId = 2,
                            Cena = 300m,
                            Ime = "Sendvic kulen",
                            MaliOpis = "lepinja, kackavalj, kulen, salata po izboru",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Sendvic.jpg",
                            SlikaUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 25,
                            CategoryId = 3,
                            Cena = 70m,
                            Ime = "Prazna palacinka",
                            MaliOpis = "Prazna palacinka bez priloga",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Palacinka.jpg",
                            SlikaUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 26,
                            CategoryId = 3,
                            Cena = 140m,
                            Ime = "Slatka palacinka orah",
                            MaliOpis = "Prilozi: orasi, smedji secer",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Palacinka.jpg",
                            SlikaUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 27,
                            CategoryId = 3,
                            Cena = 130m,
                            Ime = "Slatka palacinka med",
                            MaliOpis = "Prilog: med",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Palacinka.jpg",
                            SlikaUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 28,
                            CategoryId = 3,
                            Cena = 130m,
                            Ime = "Slatka palacinka marmelada",
                            MaliOpis = "Prilozi: marmelada po izboru(sipurak, breskva, kajsija, sljiva)",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Palacinka.jpg",
                            SlikaUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 29,
                            CategoryId = 3,
                            Cena = 140m,
                            Ime = "Slatka palacinka krem",
                            MaliOpis = "Prilog: krem",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Palacinka.jpg",
                            SlikaUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 30,
                            CategoryId = 3,
                            Cena = 160m,
                            Ime = "Slatka palacinka nutela",
                            MaliOpis = "Prilog: nutela",
                            NaStanju = true,
                            Najprodavanija = true,
                            SlikaThumbUrl = "\\Images\\Carousel\\Palacinka.jpg",
                            SlikaUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 31,
                            CategoryId = 3,
                            Cena = 230m,
                            Ime = "Slana palacinka pavlaka",
                            MaliOpis = "Prilozi: sunka, pavlaka, kackavalj",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            SlikaUrl = "\\Images\\Carousel\\SlanaPalacinka.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 32,
                            CategoryId = 3,
                            Cena = 250m,
                            Ime = "Slana palacinka kajmak",
                            MaliOpis = "Prilozi: sunka, kajmak, kackavalj",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            SlikaUrl = "\\Images\\Carousel\\SlanaPalacinka.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 33,
                            CategoryId = 3,
                            Cena = 350m,
                            Ime = "Slana palacinka prsut",
                            MaliOpis = "Prilozi: sunka, prsut, kackavalj",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            SlikaUrl = "\\Images\\Carousel\\SlanaPalacinka.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 34,
                            CategoryId = 3,
                            Cena = 300m,
                            Ime = "Slana palacinka pecenica",
                            MaliOpis = "Prilozi: sunka, pecenica, kackavalj, pavlaka",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            SlikaUrl = "\\Images\\Carousel\\SlanaPalacinka.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 35,
                            CategoryId = 3,
                            Cena = 300m,
                            Ime = "Slana palacinka kulen",
                            MaliOpis = "Prilozi: sunka, kulen, pavlaka, kackavalj",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            SlikaUrl = "\\Images\\Carousel\\SlanaPalacinka.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 36,
                            CategoryId = 3,
                            Cena = 300m,
                            Ime = "Slana palacinka suvi vrat",
                            MaliOpis = "Prilozi: sunka, suvi vrat, pavlaka, kackavalj",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            SlikaUrl = "\\Images\\Carousel\\SlanaPalacinka.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 37,
                            CategoryId = 3,
                            Cena = 300m,
                            Ime = "Slana palacinka pecenica/kulen",
                            MaliOpis = "Prilozi: pecenica, kulen, kackavalj, pavlaka",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            SlikaUrl = "\\Images\\Carousel\\SlanaPalacinka.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 38,
                            CategoryId = 4,
                            Cena = 240m,
                            Ime = "Pljeskavica",
                            MaliOpis = "160g",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            SlikaUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 39,
                            CategoryId = 4,
                            Cena = 270m,
                            Ime = "Cevapi",
                            MaliOpis = "5 komada, 160g",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            SlikaUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 40,
                            CategoryId = 4,
                            Cena = 320m,
                            Ime = "Rolovani cevapi",
                            MaliOpis = "5 komada, 200g (meso i slanina)",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            SlikaUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 41,
                            CategoryId = 4,
                            Cena = 300m,
                            Ime = "Pojacana pljeskavica",
                            MaliOpis = "200g",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            SlikaUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 42,
                            CategoryId = 4,
                            Cena = 310m,
                            Ime = "Pljeskavica sa kajmakom",
                            MaliOpis = "190g (meso i kajmak)",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            SlikaUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 43,
                            CategoryId = 4,
                            Cena = 250m,
                            Ime = "Pljeskavica u susamu",
                            MaliOpis = "180g (meso plus susam)",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            SlikaUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 44,
                            CategoryId = 4,
                            Cena = 350m,
                            Ime = "Gurmanska pljeskavica",
                            MaliOpis = "300g (meso, kackavalj, crniluk, tucana paprika)",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            SlikaUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 45,
                            CategoryId = 4,
                            Cena = 350m,
                            Ime = "Punjena pljeskavica",
                            MaliOpis = "300g (meso, kackavalj, sunka, kulen)",
                            NaStanju = true,
                            Najprodavanija = true,
                            SlikaThumbUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            SlikaUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 46,
                            CategoryId = 4,
                            Cena = 280m,
                            Ime = "Dimljena kobasica",
                            MaliOpis = "160g",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            SlikaUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 47,
                            CategoryId = 4,
                            Cena = 320m,
                            Ime = "Bela vesalica",
                            MaliOpis = "200g",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            SlikaUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 48,
                            CategoryId = 4,
                            Cena = 400m,
                            Ime = "Punjena bela vesalica",
                            MaliOpis = "300g (vesalica, senf, kackavalj, kulen, sunka)",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            SlikaUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 49,
                            CategoryId = 4,
                            Cena = 350m,
                            Ime = "Dimljeni vrat",
                            MaliOpis = "180g",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            SlikaUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 50,
                            CategoryId = 4,
                            Cena = 300m,
                            Ime = "Dimljena slanina",
                            MaliOpis = "160g",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            SlikaUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 51,
                            CategoryId = 4,
                            Cena = 230m,
                            Ime = "Pileca dzigerica",
                            MaliOpis = "160g",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            SlikaUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 52,
                            CategoryId = 4,
                            Cena = 280m,
                            Ime = "Rolovana pileca dzigerica",
                            MaliOpis = "200g (dzigerica plus slanina)",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            SlikaUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 53,
                            CategoryId = 4,
                            Cena = 300m,
                            Ime = "Pileci file",
                            MaliOpis = "200g",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            SlikaUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 54,
                            CategoryId = 4,
                            Cena = 350m,
                            Ime = "Rolovano pilece belo",
                            MaliOpis = "250g (file plus panceta)",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            SlikaUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 55,
                            CategoryId = 4,
                            Cena = 320m,
                            Ime = "Pilece belo u susamu",
                            MaliOpis = "220g (pilece belo plus susam)",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            SlikaUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 56,
                            CategoryId = 4,
                            Cena = 350m,
                            Ime = "Punjeni pileci file",
                            MaliOpis = "300g (file, kackavalj, sunka, kulen)",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            SlikaUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 57,
                            CategoryId = 4,
                            Cena = 290m,
                            Ime = "Batak",
                            MaliOpis = "200g",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            SlikaUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            VelikiOpis = ""
                        },
                        new
                        {
                            PizzaId = 58,
                            CategoryId = 4,
                            Cena = 350m,
                            Ime = "Punjeni batak",
                            MaliOpis = "300g (batak, pecurke, kackavalj, sunka)",
                            NaStanju = true,
                            Najprodavanija = false,
                            SlikaThumbUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            SlikaUrl = "\\Images\\Carousel\\Rostilj.jpg",
                            VelikiOpis = ""
                        });
                });

            modelBuilder.Entity("Caldo.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("ShoppingCartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("PizzaId")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingCartId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShoppingCartItemId");

                    b.HasIndex("PizzaId");

                    b.ToTable("ShoppingCartItem");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Caldo.Models.OrderDetail", b =>
                {
                    b.HasOne("Caldo.Models.Order", "Order")
                        .WithMany("OrderLines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Caldo.Models.Pizza", "Pizza")
                        .WithMany()
                        .HasForeignKey("PizzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Caldo.Models.Pizza", b =>
                {
                    b.HasOne("Caldo.Models.Category", "Category")
                        .WithMany("Pizzas")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Caldo.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("Caldo.Models.Pizza", "Pizza")
                        .WithMany()
                        .HasForeignKey("PizzaId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
